#!/usr/bin/env python3
"""Test script for the alerting system.

This script sends a test alert to verify that Discord and file alerts are working correctly.
"""

import sys
from pathlib import Path

# Add parent directory to path for imports
sys.path.insert(0, str(Path(__file__).parent))

from gioe_libs.alerting.alerting import AlertManager  # noqa: E402
from app.config.config import settings  # noqa: E402
from app.infrastructure.error_classifier import (  # noqa: E402
    ClassifiedError,
    ErrorSeverity,
    LLMErrorCategory,
)


def main():
    """Send a test alert."""
    print("=" * 80)
    print("Testing Alert System")
    print("=" * 80)

    # Initialize alert manager
    print(
        f"\nDiscord alerts: {'ENABLED' if settings.discord_webhook_url else 'DISABLED'}"
    )
    print(f"Alert file: {settings.alert_file_path}")

    alert_manager = AlertManager(
        alert_file_path=settings.alert_file_path,
        discord_webhook_url=settings.discord_webhook_url,
    )

    print("\nCreating test billing error...")

    # Create a test billing error
    test_error = ClassifiedError(
        category=LLMErrorCategory.BILLING_QUOTA,
        severity=ErrorSeverity.CRITICAL,
        provider="openai",
        original_error="InsufficientQuotaError",
        message=(
            "TEST ALERT: Billing or quota issue detected. "
            "Please check your OpenAI account balance and usage limits. "
            "This is a test alert from the AIQ question service."
        ),
        is_retryable=False,
    )

    print(f"Error category: {test_error.category.value}")
    print(f"Severity: {test_error.severity.value}")
    print(f"Provider: {test_error.provider}")

    print("\nSending test alert...")
    success = alert_manager.send_alert(
        test_error,
        context="This is a test alert generated by test_alerts.py to verify the alerting system is working correctly.",
    )

    print("\n" + "=" * 80)
    if success:
        print("✓ Test alert sent successfully!")
        print("\nWhat to check:")
        if settings.discord_webhook_url:
            print("  1. Check your Discord channel for the alert message")
        print(f"  2. Check alert file at: {settings.alert_file_path}")
        print("\nIf you received the alert, the system is working correctly!")
    else:
        print("✗ Test alert failed to send!")
        print("\nTroubleshooting:")
        print("  1. Check DISCORD_WEBHOOK_URL is set correctly in .env")
        print("  2. Verify the webhook URL is valid and the channel exists")
        print("  3. Check the logs for error details")

    print("=" * 80)

    # Show alert summary
    summary = alert_manager.get_alerts_summary()
    print("\nAlerts Summary:")
    print(f"  Total alerts sent: {summary['total_alerts']}")
    print(f"  Successful: {summary['successful']}")
    print(f"  Failed: {summary['failed']}")

    return 0 if success else 1


if __name__ == "__main__":
    sys.exit(main())
