"""Data models for question generation.

This module defines the data structures used throughout the question
generation pipeline, from generation to evaluation.
"""

import re
from typing import Any, Dict, List, Optional

from pydantic import BaseModel, Field, field_validator, model_validator

# Generic domain enum shared via gioe_libs
from gioe_libs.domain_types import DifficultyLevel  # noqa: F401

# AIQ-specific shared enum (single source of truth shared with backend)
from aiq_types import QuestionType  # noqa: F401


class GeneratedQuestion(BaseModel):
    """A question generated by an LLM provider.

    Attributes:
        question_text: The question text/prompt
        question_type: Type of question (pattern, logic, etc.)
        difficulty_level: Difficulty rating
        correct_answer: The correct answer
        answer_options: List of answer options for multiple choice (optional)
        explanation: Explanation of why the answer is correct (optional)
        stimulus: Content to memorize before answering (for memory questions)
        metadata: Additional metadata about the question
        source_llm: Which LLM generated this question
        source_model: Specific model identifier
    """

    question_text: str = Field(..., min_length=10)
    question_type: QuestionType
    difficulty_level: DifficultyLevel
    correct_answer: str = Field(..., min_length=1)
    answer_options: Optional[List[str]] = None
    explanation: Optional[str] = None
    stimulus: Optional[str] = None
    sub_type: Optional[str] = None
    metadata: Dict[str, Any] = Field(default_factory=dict)
    source_llm: str = Field(..., min_length=1)  # "openai", "anthropic", "google"
    source_model: str = Field(..., min_length=1)  # Specific model name

    @field_validator("answer_options")
    @classmethod
    def validate_answer_options(
        cls, v: Optional[List[str]], info
    ) -> Optional[List[str]]:
        """Validate that correct_answer is in answer_options if provided."""
        if v is not None:
            if len(v) < 2:
                raise ValueError("Must have at least 2 answer options if provided")
            correct = info.data.get("correct_answer")
            if correct and correct not in v:
                raise ValueError(
                    f"correct_answer '{correct}' must be in answer_options"
                )
        return v

    @model_validator(mode="after")
    def validate_stimulus_for_memory_questions(self) -> "GeneratedQuestion":
        """Validate that memory questions have a non-empty stimulus field."""
        if self.question_type == QuestionType.MEMORY:
            if not self.stimulus or not self.stimulus.strip():
                raise ValueError(
                    "Memory questions require a non-empty 'stimulus' field "
                    "containing content for the user to memorize"
                )
        return self

    @model_validator(mode="after")
    def validate_no_answer_in_question(self) -> "GeneratedQuestion":
        """Reject questions where the correct answer or any option text leaks into the question body."""
        question_lower = self.question_text.lower()
        if self.correct_answer.lower() in question_lower:
            raise ValueError(
                f"correct_answer '{self.correct_answer}' appears as a substring of "
                "question_text — the answer must not be revealed in the question body"
            )
        if self.answer_options:
            for option in self.answer_options:
                if option.lower() in question_lower:
                    raise ValueError(
                        f"answer_option '{option}' appears as a substring of "
                        "question_text — answer options must not appear in the question body"
                    )
        return self

    # Legitimate uppercase acronyms that should not be normalized
    _LEGIT_UPPER = frozenset(
        {
            "DNA",
            "RNA",
            "IQ",
            "AIQ",
            "CEO",
            "GDP",
            "USA",
            "UK",
            "EU",
            "NASA",
            "HIV",
            "AIDS",
            "PDF",
            "HTML",
            "CSS",
            "SQL",
            "API",
            "CPU",
            "RAM",
            "ROM",
            "LED",
            "UFO",
            "PhD",
            "MBA",
            "GPA",
            "SAT",
            "ACT",
            "GCD",
            "LCM",
            "PIN",
            "SUV",
            "BCE",
            "ABC",
            "AM",
            "PM",
            "AD",
            "BC",
            "II",
            "III",
            "IV",
            "VI",
            "VII",
            "VIII",
            "IX",
            "XI",
            "XII",
            "XX",
        }
    )
    _GRID_PATTERNS = frozenset({"XXX", "XXXX", "XXXXX"})

    @model_validator(mode="after")
    def normalize_all_caps_words(self) -> "GeneratedQuestion":
        """Auto-normalize ALL CAPS words to bold lowercase in text fields.

        Converts ALL CAPS emphasis to **bold** markdown in question_text
        and stimulus, and to title case in answer fields.
        """

        def bold_caps(text: str) -> str:
            text = re.sub(
                r"MEMORIZE THIS SEQUENCE:", "**Memorize this sequence:**", text
            )

            def _replace(m: re.Match) -> str:
                w = m.group(0)
                if w in self._LEGIT_UPPER or w in self._GRID_PATTERNS:
                    return w
                return f"**{w.lower()}**"

            return re.sub(r"\b[A-Z]{3,}\b", _replace, text)

        def title_caps(text: str) -> str:
            def _replace(m: re.Match) -> str:
                w = m.group(0)
                if w in self._LEGIT_UPPER or w in self._GRID_PATTERNS:
                    return w
                return w.capitalize()

            return re.sub(r"\b[A-Z]{3,}\b", _replace, text)

        self.question_text = bold_caps(self.question_text)
        self.correct_answer = title_caps(self.correct_answer)
        if self.answer_options:
            self.answer_options = [title_caps(opt) for opt in self.answer_options]
        if self.stimulus:
            self.stimulus = bold_caps(self.stimulus)
        return self

    def to_dict(self) -> Dict[str, Any]:
        """Convert to dictionary for database insertion."""
        return {
            "question_text": self.question_text,
            "question_type": self.question_type.value,
            "difficulty_level": self.difficulty_level.value,
            "correct_answer": self.correct_answer,
            "answer_options": self.answer_options,
            "explanation": self.explanation,
            "stimulus": self.stimulus,
            "sub_type": self.sub_type,
            "metadata": self.metadata,
            "source_llm": self.source_llm,
            "source_model": self.source_model,
        }


class EvaluationScore(BaseModel):
    """Evaluation score from an judge model.

    Attributes:
        clarity_score: Score for clarity and lack of ambiguity (0.0 to 1.0)
        difficulty_score: Score for appropriate difficulty (0.0 to 1.0)
        validity_score: Score for validity as IQ test question (0.0 to 1.0)
        formatting_score: Score for proper formatting (0.0 to 1.0)
        creativity_score: Score for novelty and interest (0.0 to 1.0)
        overall_score: Weighted overall score (0.0 to 1.0)
        feedback: Optional textual feedback from judge
    """

    clarity_score: float = Field(..., ge=0.0, le=1.0)
    difficulty_score: float = Field(..., ge=0.0, le=1.0)
    validity_score: float = Field(..., ge=0.0, le=1.0)
    formatting_score: float = Field(..., ge=0.0, le=1.0)
    creativity_score: float = Field(..., ge=0.0, le=1.0)
    overall_score: float = Field(..., ge=0.0, le=1.0)
    feedback: Optional[str] = None


class EvaluatedQuestion(BaseModel):
    """A generated question with its evaluation score.

    Attributes:
        question: The generated question
        evaluation: Evaluation score from judge
        judge_model: Which judge model evaluated this
        approved: Whether the question meets the threshold
    """

    question: GeneratedQuestion
    evaluation: EvaluationScore
    judge_model: str
    approved: bool

    @property
    def is_approved(self) -> bool:
        """Check if question is approved."""
        return self.approved


class GenerationBatch(BaseModel):
    """A batch of generated questions.

    Attributes:
        questions: List of generated questions
        question_type: Type of questions in this batch
        batch_size: Number of questions requested
        generation_timestamp: When this batch was generated
        metadata: Additional batch metadata
    """

    questions: List[GeneratedQuestion]
    question_type: QuestionType
    batch_size: int
    generation_timestamp: str
    metadata: Dict[str, Any] = Field(default_factory=dict)

    def __len__(self) -> int:
        """Get number of questions in batch."""
        return len(self.questions)
