disabled_rules:
  - trailing_whitespace
opt_in_rules:
  - empty_count
  - empty_string
  - unused_optional_binding
  - missing_docs
analyzer_rules:
  - unused_declaration

excluded:
  - Pods
  - .build
  - build
  - DerivedData
  - AIQ.xcodeproj
  - AIQTests

line_length:
  warning: 120
  error: 150

file_length:
  warning: 800
  error: 1000

type_body_length:
  warning: 475
  error: 525

function_body_length:
  warning: 50
  error: 100

large_tuple:
  warning: 3
  error: 4

identifier_name:
  min_length:
    warning: 2
  max_length:
    warning: 50
    error: 60
  excluded:
    - id
    - x
    - y
    - z

cyclomatic_complexity:
  warning: 10
  error: 20

nesting:
  type_level:
    warning: 2

reporter: "xcode"

# Custom rules for project-specific patterns
custom_rules:
  handle_error_weak_self:
    name: "HandleError Weak Self"
    regex: 'handleError\([^}]+\{\s*\n\s*await self\.'
    message: "handleError retry closure must use [weak self] to avoid retain cycles. See CODING_STANDARDS.md 'Memory Management in Error Handlers'"
    severity: error

  stateobject_with_shared:
    name: "StateObject with Singleton"
    regex: '@StateObject\s+(?:private\s+)?var\s+\w+\s*=\s*\w+\.shared\s*$'
    message: "Do not use @StateObject with singletons (.shared). Use @ObservedObject instead. See CODING_STANDARDS.md 'Common Property Wrapper Anti-Patterns'"
    severity: error
