"""add_client_run_id_to_question_generation_runs

Revision ID: 19fad4f4ae64
Revises: 977d2850e07d
Create Date: 2026-03-29 14:05:24.699735

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "19fad4f4ae64"
down_revision: Union[str, None] = "977d2850e07d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "question_generation_runs",
        sa.Column("client_run_id", sa.String(length=100), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("question_generation_runs", "client_run_id")
    # ### end Alembic commands ###
