"""Add demographic fields to User model for norming study (P13-001)

Revision ID: 2db42381c86f
Revises: d86e6798032c
Create Date: 2025-11-25 20:29:37.025706

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "2db42381c86f"
down_revision: Union[str, None] = "d86e6798032c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Create ENUM type for education_level
    education_level_enum = sa.Enum(
        "HIGH_SCHOOL",
        "SOME_COLLEGE",
        "ASSOCIATES",
        "BACHELORS",
        "MASTERS",
        "DOCTORATE",
        "PREFER_NOT_TO_SAY",
        name="educationlevel",
    )
    education_level_enum.create(op.get_bind(), checkfirst=True)

    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("birth_year", sa.Integer(), nullable=True))
    op.add_column(
        "users", sa.Column("education_level", education_level_enum, nullable=True)
    )
    op.add_column("users", sa.Column("country", sa.String(length=100), nullable=True))
    op.add_column("users", sa.Column("region", sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "region")
    op.drop_column("users", "country")
    op.drop_column("users", "education_level")
    op.drop_column("users", "birth_year")
    # ### end Alembic commands ###

    # Drop ENUM type
    sa.Enum(name="educationlevel").drop(op.get_bind(), checkfirst=True)
