"""Add confidence interval fields to test_results (P11-008)

Revision ID: 555e7c724405
Revises: 88562b225bce
Create Date: 2025-11-16 15:18:47.552118

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "555e7c724405"
down_revision: Union[str, None] = "88562b225bce"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    # Add confidence interval fields to test_results table (P11-008)
    # These fields prepare for Phase 12 when we can calculate actual SEM
    # and provide confidence intervals for IQ scores
    op.add_column(
        "test_results", sa.Column("standard_error", sa.Float(), nullable=True)
    )  # Standard Error of Measurement
    op.add_column(
        "test_results", sa.Column("ci_lower", sa.Integer(), nullable=True)
    )  # Lower bound of confidence interval
    op.add_column(
        "test_results", sa.Column("ci_upper", sa.Integer(), nullable=True)
    )  # Upper bound of confidence interval
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("test_results", "ci_upper")
    op.drop_column("test_results", "ci_lower")
    op.drop_column("test_results", "standard_error")
    # ### end Alembic commands ###
