"""Add question_generation_runs table

Revision ID: 5f40f8572f3f
Revises: a2dc431c2d70
Create Date: 2025-12-04 20:41:12.584407

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "5f40f8572f3f"
down_revision: Union[str, None] = "a2dc431c2d70"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "question_generation_runs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("duration_seconds", sa.Float(), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "RUNNING",
                "SUCCESS",
                "PARTIAL_FAILURE",
                "FAILED",
                name="generationrunstatus",
            ),
            nullable=False,
        ),
        sa.Column("exit_code", sa.Integer(), nullable=True),
        sa.Column("questions_requested", sa.Integer(), nullable=False),
        sa.Column("questions_generated", sa.Integer(), nullable=False),
        sa.Column("generation_failures", sa.Integer(), nullable=False),
        sa.Column("generation_success_rate", sa.Float(), nullable=True),
        sa.Column("questions_evaluated", sa.Integer(), nullable=False),
        sa.Column("questions_approved", sa.Integer(), nullable=False),
        sa.Column("questions_rejected", sa.Integer(), nullable=False),
        sa.Column("approval_rate", sa.Float(), nullable=True),
        sa.Column("avg_judge_score", sa.Float(), nullable=True),
        sa.Column("min_judge_score", sa.Float(), nullable=True),
        sa.Column("max_judge_score", sa.Float(), nullable=True),
        sa.Column("duplicates_found", sa.Integer(), nullable=False),
        sa.Column("exact_duplicates", sa.Integer(), nullable=False),
        sa.Column("semantic_duplicates", sa.Integer(), nullable=False),
        sa.Column("duplicate_rate", sa.Float(), nullable=True),
        sa.Column("questions_inserted", sa.Integer(), nullable=False),
        sa.Column("insertion_failures", sa.Integer(), nullable=False),
        sa.Column("overall_success_rate", sa.Float(), nullable=True),
        sa.Column("total_errors", sa.Integer(), nullable=False),
        sa.Column("total_api_calls", sa.Integer(), nullable=False),
        sa.Column(
            "provider_metrics", postgresql.JSON(astext_type=sa.Text()), nullable=True
        ),
        sa.Column(
            "type_metrics", postgresql.JSON(astext_type=sa.Text()), nullable=True
        ),
        sa.Column(
            "difficulty_metrics", postgresql.JSON(astext_type=sa.Text()), nullable=True
        ),
        sa.Column(
            "error_summary", postgresql.JSON(astext_type=sa.Text()), nullable=True
        ),
        sa.Column("prompt_version", sa.String(length=50), nullable=True),
        sa.Column("arbiter_config_version", sa.String(length=50), nullable=True),
        sa.Column("min_judge_score_threshold", sa.Float(), nullable=True),
        sa.Column("environment", sa.String(length=20), nullable=True),
        sa.Column("triggered_by", sa.String(length=50), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.execute(
        "CREATE INDEX IF NOT EXISTS ix_qgr_environment"
        " ON question_generation_runs (environment)"
    )
    op.execute(
        "CREATE INDEX IF NOT EXISTS ix_qgr_overall_success"
        " ON question_generation_runs (overall_success_rate)"
    )
    op.execute(
        "CREATE INDEX IF NOT EXISTS ix_qgr_started_at"
        " ON question_generation_runs (started_at)"
    )
    op.execute(
        "CREATE INDEX IF NOT EXISTS ix_qgr_status"
        " ON question_generation_runs (status)"
    )
    op.execute(
        "CREATE INDEX IF NOT EXISTS ix_question_generation_runs_id"
        " ON question_generation_runs (id)"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DROP INDEX IF EXISTS ix_question_generation_runs_id")
    op.execute("DROP INDEX IF EXISTS ix_qgr_status")
    op.execute("DROP INDEX IF EXISTS ix_qgr_started_at")
    op.execute("DROP INDEX IF EXISTS ix_qgr_overall_success")
    op.execute("DROP INDEX IF EXISTS ix_qgr_environment")
    op.drop_table("question_generation_runs")
    # Drop the enum type created by the upgrade
    op.execute("DROP TYPE IF EXISTS generationrunstatus")
    # ### end Alembic commands ###
