"""Add composition_metadata to test_sessions

Revision ID: 68ba60e646f3
Revises: c44a9878534d
Create Date: 2025-11-16 09:01:19.045549

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "68ba60e646f3"
down_revision: Union[str, None] = "c44a9878534d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "test_sessions",
        sa.Column(
            "composition_metadata",
            postgresql.JSON(astext_type=sa.Text()),
            nullable=True,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("test_sessions", "composition_metadata")
    # ### end Alembic commands ###
