"""Add validity override fields to test_results for CD-017

Revision ID: 79293ccfff14
Revises: 58757aab56ca
Create Date: 2025-12-12 20:06:32.340055

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "79293ccfff14"
down_revision: Union[str, None] = "58757aab56ca"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "test_results", sa.Column("validity_override_reason", sa.Text(), nullable=True)
    )
    op.add_column(
        "test_results",
        sa.Column("validity_overridden_at", sa.DateTime(timezone=True), nullable=True),
    )
    op.add_column(
        "test_results", sa.Column("validity_overridden_by", sa.Integer(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("test_results", "validity_overridden_by")
    op.drop_column("test_results", "validity_overridden_at")
    op.drop_column("test_results", "validity_override_reason")
    # ### end Alembic commands ###
