"""Add test_session_id to user_questions table

Revision ID: a2dc431c2d70
Revises: 29c0f32c19ea
Create Date: 2025-11-29 08:54:20.465792

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "a2dc431c2d70"
down_revision: Union[str, None] = "29c0f32c19ea"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user_questions", sa.Column("test_session_id", sa.Integer(), nullable=True)
    )
    op.execute(
        "CREATE INDEX IF NOT EXISTS ix_user_questions_test_session_id"
        " ON user_questions (test_session_id)"
    )
    op.create_foreign_key(
        None,
        "user_questions",
        "test_sessions",
        ["test_session_id"],
        ["id"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "user_questions", type_="foreignkey")
    op.execute("DROP INDEX IF EXISTS ix_user_questions_test_session_id")
    op.drop_column("user_questions", "test_session_id")
    # ### end Alembic commands ###
