"""Initial schema with users, questions, test sessions, responses, and results

Revision ID: d7ecc2b8d347
Revises:
Create Date: 2025-11-01 21:16:47.535868

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "d7ecc2b8d347"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "questions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("question_text", sa.Text(), nullable=False),
        sa.Column(
            "question_type",
            sa.Enum(
                "PATTERN",
                "LOGIC",
                "SPATIAL",
                "MATH",
                "VERBAL",
                "MEMORY",
                name="questiontype",
            ),
            nullable=False,
        ),
        sa.Column(
            "difficulty_level",
            sa.Enum("EASY", "MEDIUM", "HARD", name="difficultylevel"),
            nullable=False,
        ),
        sa.Column("correct_answer", sa.String(length=500), nullable=False),
        sa.Column(
            "answer_options", postgresql.JSON(astext_type=sa.Text()), nullable=True
        ),
        sa.Column("explanation", sa.Text(), nullable=True),
        sa.Column(
            "question_metadata", postgresql.JSON(astext_type=sa.Text()), nullable=True
        ),
        sa.Column("source_llm", sa.String(length=100), nullable=True),
        sa.Column("judge_score", sa.Float(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.execute("CREATE INDEX IF NOT EXISTS ix_questions_id ON questions (id)")
    op.execute(
        "CREATE INDEX IF NOT EXISTS ix_questions_is_active ON questions (is_active)"
    )
    op.execute(
        "CREATE INDEX IF NOT EXISTS ix_questions_type ON questions (question_type)"
    )
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("password_hash", sa.String(length=255), nullable=False),
        sa.Column("first_name", sa.String(length=100), nullable=True),
        sa.Column("last_name", sa.String(length=100), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("last_login_at", sa.DateTime(), nullable=True),
        sa.Column("notification_enabled", sa.Boolean(), nullable=False),
        sa.Column("apns_device_token", sa.String(length=255), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.execute("CREATE UNIQUE INDEX IF NOT EXISTS ix_users_email ON users (email)")
    op.execute("CREATE INDEX IF NOT EXISTS ix_users_id ON users (id)")
    op.create_table(
        "test_sessions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("started_at", sa.DateTime(), nullable=False),
        sa.Column("completed_at", sa.DateTime(), nullable=True),
        sa.Column(
            "status",
            sa.Enum("IN_PROGRESS", "COMPLETED", "ABANDONED", name="teststatus"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.execute("CREATE INDEX IF NOT EXISTS ix_test_sessions_id ON test_sessions (id)")
    op.create_table(
        "user_questions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("question_id", sa.Integer(), nullable=False),
        sa.Column("seen_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["question_id"], ["questions.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "question_id", name="uq_user_question"),
    )
    op.execute("CREATE INDEX IF NOT EXISTS ix_user_questions_id ON user_questions (id)")
    op.execute(
        "CREATE INDEX IF NOT EXISTS ix_user_questions_user_id ON user_questions (user_id)"
    )
    op.create_table(
        "responses",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("test_session_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("question_id", sa.Integer(), nullable=False),
        sa.Column("user_answer", sa.String(length=500), nullable=False),
        sa.Column("is_correct", sa.Boolean(), nullable=False),
        sa.Column("answered_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["question_id"], ["questions.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["test_session_id"], ["test_sessions.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.execute("CREATE INDEX IF NOT EXISTS ix_responses_id ON responses (id)")
    op.create_table(
        "test_results",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("test_session_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("iq_score", sa.Integer(), nullable=False),
        sa.Column("total_questions", sa.Integer(), nullable=False),
        sa.Column("correct_answers", sa.Integer(), nullable=False),
        sa.Column("completion_time_seconds", sa.Integer(), nullable=True),
        sa.Column("completed_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["test_session_id"], ["test_sessions.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("test_session_id"),
    )
    op.execute("CREATE INDEX IF NOT EXISTS ix_test_results_id ON test_results (id)")
    op.execute(
        "CREATE INDEX IF NOT EXISTS ix_test_results_user_id ON test_results (user_id)"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DROP INDEX IF EXISTS ix_test_results_user_id")
    op.execute("DROP INDEX IF EXISTS ix_test_results_id")
    op.drop_table("test_results")
    op.execute("DROP INDEX IF EXISTS ix_responses_id")
    op.drop_table("responses")
    op.execute("DROP INDEX IF EXISTS ix_user_questions_user_id")
    op.execute("DROP INDEX IF EXISTS ix_user_questions_id")
    op.drop_table("user_questions")
    op.execute("DROP INDEX IF EXISTS ix_test_sessions_id")
    op.drop_table("test_sessions")
    op.execute("DROP INDEX IF EXISTS ix_users_id")
    op.execute("DROP INDEX IF EXISTS ix_users_email")
    op.drop_table("users")
    op.execute("DROP INDEX IF EXISTS ix_questions_type")
    op.execute("DROP INDEX IF EXISTS ix_questions_is_active")
    op.execute("DROP INDEX IF EXISTS ix_questions_id")
    op.drop_table("questions")
    # ### end Alembic commands ###
