"""Add question_embedding column to questions table

Revision ID: w0825k5ogsiy
Revises: ea5cc7f53b30
Create Date: 2026-01-21 00:00:00.000000

Rationale (TASK-433):
The current implementation computes embeddings on-the-fly during question
deduplication, which is increasingly expensive as the question pool grows.
Each deduplication run requires O(n) embedding API calls for n existing questions.

This migration adds question_embedding column to store pre-computed embeddings,
enabling:
- One-time embedding computation at question creation
- O(1) embedding retrieval during deduplication (no API calls)
- Significant cost reduction as question pool scales
- Faster deduplication process (no API latency)

The column stores a 1536-dimensional float array generated by OpenAI's
text-embedding-3-small model. PostgreSQL's ARRAY type provides efficient
storage and retrieval without requiring pgvector extension.

Existing questions will have NULL embeddings initially. A separate backfill
script will populate embeddings for existing questions in batches.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = "w0825k5ogsiy"
down_revision: Union[str, None] = "ea5cc7f53b30"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


# Embedding dimension for text-embedding-3-small model
EMBEDDING_DIMENSION = 1536


def upgrade() -> None:
    """Add question_embedding column to questions table.

    Adds a column to store pre-computed text embeddings as a PostgreSQL
    ARRAY of floats. The column is nullable to support:
    - Gradual rollout (existing questions start with NULL)
    - Backfill operation (populate embeddings in batches)
    - Graceful degradation (fall back to on-demand computation if NULL)
    """
    op.add_column(
        "questions",
        sa.Column(
            "question_embedding",
            postgresql.ARRAY(sa.Float),
            nullable=True,
            comment=f"Pre-computed embedding vector ({EMBEDDING_DIMENSION}D) for semantic similarity",
        ),
    )


def downgrade() -> None:
    """Remove question_embedding column from questions table.

    Drops the embedding column, reverting to on-demand embedding computation.
    This is safe as embeddings can always be regenerated from question_text.
    """
    op.drop_column("questions", "question_embedding")
